watch:
  asset: BTC
  currency: USDT
  mode: backtest # backtest | importer | realtime
  timeframe: '1w'
  scan: true
  warmup:
    candleCount: 52

storage:
  type: sqlite
  database: ./db/gekko.sql

strategy:
  name: MACD
  short: 12
  long: 26
  signal: 9
  thresholds:
    up: 750
    down: -750
    persistence: 3

plugins:
  - name: TradingAdvisor
    strategyName: MACD

  - name: PaperTrader
    simulationBalance: # start balance, on what the current balance is compared with
      # these are in the unit types configured in the watcher.
      asset: 0
      currency: 1000
    # how much fee in % does each trade cost?
    feeMaker: 0.15
    feeTaker: 0.25
    feeUsing: maker

  - name: PerformanceAnalyzer
    enableConsoleTable: true
    riskFreeReturn: 5
