watch:
  asset: BTC
  currency: USDT
  mode: backtest # backtest | importer | realtime
  timeframe: '1w'
  scan: true
  warmup:
    candleCount: 52

storage:
  type: sqlite
  database: ./db/binance-BTC_USDT.sql

strategy:
  name: MACD
  short: 12
  long: 26
  signal: 9
  thresholds:
    up: 750
    down: -750
    persistence: 3

plugins:
  - name: TradingAdvisor
    strategyName: MACD

  - name: PaperTrader

  - name: PerformanceAnalyzer
    enableConsoleTable: true
