watch:
  asset: BTC
  currency: USDT
  mode: backtest
  timeframe: 4h
  warmup:
    candleCount: 366
  daterange:
    start: '2024-05-01T00:00:00.000Z'
    end: '2025-07-01T00:00:00.000Z'

storage:
  type: sqlite
  database: ./db/binance-BTC_USDT.sql

strategy:
  name: EMARibbon
  src: 'ohlc4'
  count: 4
  start: 14
  step: 1

plugins:
  - name: TradingAdvisor
    strategyName: EMARibbon

  - name: PaperTrader

  - name: PerformanceAnalyzer
    enableConsoleTable: true
