watch:
  asset: BTC
  currency: USDT
  mode: backtest
  scan: true

storage:
  type: sqlite
  database: ./db/gekko.sql

strategy:
  name: WM
  rsiPeriod: 21
  period: 12
  lookBackLeft: 3
  lookBackRight: 1
  upper: 5
  lower: 3

plugins:
  - name: TradingAdvisor
    strategyName: WM
    timeframe: '1w' # 1 week
    historySize: 0
