watch:
  asset: BTC
  currency: USDT
  mode: realtime # backtest | importer | realtime
  timeframe: '1d'
  warmup:
    candleCount: 365

exchange:
  name: dummy-cex

strategy:
  name: DEMA
  period: 12
  thresholds:
    up: 100
    down: -150

plugins:
  - name: TradingAdvisor
    strategyName: DEMA

  - name: Trader

  - name: PerformanceAnalyzer
    riskFreeReturn: 5
