watch:
  asset: BTC
  currency: USDT
  mode: realtime # backtest | importer | realtime

broker:
  name: binance

strategy:
  name: DEMA
  period: 12
  thresholds:
    up: 100
    down: -150

plugins:
  - name: TradingAdvisor
    strategyName: DEMA
    timeframe: '1m'
    historySize: 5

  - name: PaperTrader
    simulationBalance: # start balance, on what the current balance is compared with
      # these are in the unit types configured in the watcher.
      asset: 1
      currency: 100
    # how much fee in % does each trade cost?
    feeMaker: 0.15
    feeTaker: 0.25
    feeUsing: maker

  - name: PerformanceAnalyzer
    riskFreeReturn: 5
