export type Tag =
  | 'bot'
  | 'exchange'
  | 'configuration'
  | 'core'
  | 'fetcher'
  | 'gekko'
  | 'order'
  | 'injecter'
  | 'performance analyzer'
  | 'performance reporter'
  | 'pipeline'
  | 'event'
  | 'storage'
  | 'strategy'
  | 'stream'
  | 'event subscriber'
  | 'supervision'
  | 'trader'
  | 'trading advisor';
